/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef friendslistservice_CONSTANTS_H
#define friendslistservice_CONSTANTS_H

#include "friendslistservice_types.h"

namespace friendslistservice {

class friendslistserviceConstants {
 public:
  friendslistserviceConstants();

};

extern const friendslistserviceConstants g_friendslistservice_constants;

} // namespace

#endif
