/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "friendslistservice_constants.h"

namespace friendslistservice {

const friendslistserviceConstants g_friendslistservice_constants;

friendslistserviceConstants::friendslistserviceConstants() {
}

} // namespace

